# Generated by Django 6.0.6 on 2026-06-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
